### ISSUE TITLE
Dependency on old passport is breaking code that uses newer passport.

### ISSUE THREAD

**Issue by jdfm** [jaredhanson/passport-openid#28]
I was testing the LocalStrategy for a login page I was building and I was expecting to see the req object in the passport.serializeUser method, but it was never there, after some sleuthing I found that the version of passport that is being included with passport-openid is substituting the newer version of passport that I actually wanted to use. Code that is being used:

node_modules/passport-openid/node_modules/passport/lib/passport/http/request.js

Code that should be in current use instead:

node_modules/passport/lib/passport/http/request.js

**Comment by filso** [comment]
+1

**Comment by jaredhanson** [comment]
Published package with fix to npm as `passport-openid@0.4.0`.

**Comment by filso** [comment]
@jaredhanson could you also update package.json in passport-paypal to new version?
https://github.com/jaredhanson/passport-paypal/blob/master/package.json#L25
